// frontend/src/app/features/categories/categories.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';

@Component({
  selector: 'app-category-dialog',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule
  ],
  template: `
    <h2 mat-dialog-title>Create Category</h2>
    <mat-dialog-content>
      <form [formGroup]="form" class="d-flex flex-column gap-2 mt-2">
        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Category Name</mat-label>
          <input matInput formControlName="name">
        </mat-form-field>
        
        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Type</mat-label>
          <mat-select formControlName="type">
            <mat-option value="FIXED">Fixed Expense</mat-option>
            <mat-option value="MONTHLY_RESET">Monthly Budget</mat-option>
            <mat-option value="CUSTOM">Custom</mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Budget / Configured Amount (₹)</mat-label>
          <input matInput type="number" formControlName="configuredAmount">
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Color</mat-label>
          <input matInput type="color" formControlName="color" style="height: 40px;">
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Description (Optional)</mat-label>
          <input matInput formControlName="description">
        </mat-form-field>
      </form>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-raised-button color="primary" [disabled]="form.invalid" (click)="save()">Save</button>
    </mat-dialog-actions>
  `,
  styles: [`
    .flex-column { flex-direction: column; }
    .gap-2 { gap: 16px; }
  `]
})
export class CategoryDialogComponent {
  fb = inject(FormBuilder);
  dialogRef = inject(MatDialogRef<CategoryDialogComponent>);

  form = this.fb.group({
    name: ['', Validators.required],
    type: ['MONTHLY_RESET', Validators.required],
    configuredAmount: [0, [Validators.required, Validators.min(0)]],
    color: ['#1976d2', Validators.required],
    description: ['']
  });

  save() {
    if (this.form.valid) {
      this.dialogRef.close(this.form.value);
    }
  }
}

@Component({
  selector: 'app-categories',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatDialogModule
  ],
  providers: [CurrencyPipe],
  template: `
    <div class="header-section d-flex justify-between align-center mb-3">
      <h2>Categories</h2>
      <button mat-raised-button color="primary" (click)="openCreateDialog()">
        <mat-icon>add</mat-icon> Add Category
      </button>
    </div>

    <mat-card>
      <mat-card-content class="p-0">
        <table mat-table [dataSource]="categories" class="w-100">
          
          <ng-container matColumnDef="color">
            <th mat-header-cell *matHeaderCellDef> Color </th>
            <td mat-cell *matCellDef="let element">
              <span class="color-dot" [style.backgroundColor]="element.color"></span>
            </td>
          </ng-container>

          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef> Name </th>
            <td mat-cell *matCellDef="let element"> {{element.name}} </td>
          </ng-container>

          <ng-container matColumnDef="type">
            <th mat-header-cell *matHeaderCellDef> Type </th>
            <td mat-cell *matCellDef="let element"> {{element.type}} </td>
          </ng-container>

          <ng-container matColumnDef="amount">
            <th mat-header-cell *matHeaderCellDef> Configured Amount </th>
            <td mat-cell *matCellDef="let element"> {{element.configuredAmount | currency:'INR':'symbol':'1.0-0'}} </td>
          </ng-container>

          <ng-container matColumnDef="status">
            <th mat-header-cell *matHeaderCellDef> Status </th>
            <td mat-cell *matCellDef="let element">
              <span class="badge" [ngClass]="element.isActive ? 'badge-active' : 'badge-inactive'">
                {{element.isActive ? 'Active' : 'Archived'}}
              </span>
            </td>
          </ng-container>

          <ng-container matColumnDef="actions">
            <th mat-header-cell *matHeaderCellDef> Actions </th>
            <td mat-cell *matCellDef="let element">
              <button mat-icon-button color="warn" (click)="archive(element)" *ngIf="element.isActive" title="Archive">
                <mat-icon>archive</mat-icon>
              </button>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumns;" [ngClass]="{'row-archived': !row.isActive}"></tr>
        </table>
        <div *ngIf="categories.length === 0" class="text-center p-3 text-muted">
          No categories found. Start by adding one.
        </div>
      </mat-card-content>
    </mat-card>
  `,
  styles: [`
    .p-0 { padding: 0 !important; }
    .p-3 { padding: 24px; }
    .color-dot {
      display: inline-block;
      width: 16px;
      height: 16px;
      border-radius: 50%;
    }
    .badge {
      padding: 4px 8px;
      border-radius: 12px;
      font-size: 0.75rem;
      font-weight: 500;
    }
    .badge-active { background-color: #e8f5e9; color: #2e7d32; }
    .badge-inactive { background-color: #f5f5f5; color: #757575; }
    .row-archived { opacity: 0.6; }
  `]
})
export class CategoriesComponent implements OnInit {
  http = inject(HttpClient);
  dialog = inject(MatDialog);
  snackBar = inject(MatSnackBar);

  categories: any[] = [];
  displayedColumns = ['color', 'name', 'type', 'amount', 'status', 'actions'];

  ngOnInit() {
    this.loadCategories();
  }

  loadCategories() {
    this.http.get('http://localhost:3000/api/categories').subscribe({
      next: (res: any) => {
        this.categories = res.data;
      }
    });
  }

  openCreateDialog() {
    const dialogRef = this.dialog.open(CategoryDialogComponent, { width: '400px' });
    
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.http.post('http://localhost:3000/api/categories', result).subscribe({
          next: () => {
            this.snackBar.open('Category created successfully', 'Close', { duration: 3000 });
            this.loadCategories();
          },
          error: (err) => {
            this.snackBar.open(err.error?.message || 'Error creating category', 'Close', { duration: 3000 });
          }
        });
      }
    });
  }

  archive(category: any) {
    if (confirm(`Are you sure you want to archive ${category.name}?`)) {
      this.http.patch(`http://localhost:3000/api/categories/${category.id}/archive`, {}).subscribe({
        next: () => {
          this.snackBar.open('Category archived successfully', 'Close', { duration: 3000 });
          this.loadCategories();
        }
      });
    }
  }
}

// frontend/src/app/(app)/categories/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { useToast } from '@/components/Toast';
import Modal from '@/components/Modal';
import styles from './categories.module.css';

function fmt(n: number) {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
}

interface CategoryForm {
  name: string;
  type: string;
  configuredAmount: string;
  color: string;
  description: string;
}

const emptyForm: CategoryForm = {
  name: '',
  type: 'MONTHLY_RESET',
  configuredAmount: '0',
  color: '#6366f1',
  description: '',
};

export default function CategoriesPage() {
  const showToast = useToast();
  const [categories, setCategories] = useState<any[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [form, setForm] = useState<CategoryForm>(emptyForm);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => { loadCategories(); }, []);

  async function loadCategories() {
    try {
      const res = await api.get('/categories');
      setCategories(res.data);
    } catch {}
  }

  function openCreate() {
    setForm({ ...emptyForm });
    setFormErrors({});
    setIsModalOpen(true);
  }

  function validateForm() {
    const e: Record<string, string> = {};
    if (!form.name.trim()) e.name = 'Category name is required';
    if (!form.type) e.type = 'Type is required';
    if (Number(form.configuredAmount) < 0) e.configuredAmount = 'Amount must be ≥ 0';
    setFormErrors(e);
    return Object.keys(e).length === 0;
  }

  async function handleSave() {
    if (!validateForm()) return;
    setIsSaving(true);
    try {
      await api.post('/categories', {
        name: form.name,
        type: form.type,
        configuredAmount: Number(form.configuredAmount),
        color: form.color,
        description: form.description,
      });
      showToast('Category created successfully', 'success');
      setIsModalOpen(false);
      loadCategories();
    } catch (err: any) {
      showToast(err.body?.message || 'Error creating category', 'error');
    } finally {
      setIsSaving(false);
    }
  }

  async function handleArchive(category: any) {
    if (!confirm(`Archive "${category.name}"?`)) return;
    try {
      await api.patch(`/categories/${category.id}/archive`, {});
      showToast('Category archived', 'success');
      loadCategories();
    } catch {
      showToast('Failed to archive category', 'error');
    }
  }

  const typeLabel: Record<string, string> = {
    FIXED: 'Fixed Expense',
    MONTHLY_RESET: 'Monthly Budget',
    CUSTOM: 'Custom',
  };

  return (
    <div className="fade-in">
      <div className="page-header">
        <h1 className="page-title">Categories</h1>
        <button className="btn btn-primary" onClick={openCreate}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" />
          </svg>
          Add Category
        </button>
      </div>

      <div className="card" style={{ padding: 0 }}>
        <div className="table-wrapper" style={{ border: 'none', borderRadius: 'var(--radius-lg)' }}>
          <table className="data-table">
            <thead>
              <tr>
                <th>Color</th>
                <th>Name</th>
                <th>Type</th>
                <th>Configured Amount</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {categories.length === 0 ? (
                <tr>
                  <td colSpan={6} className="text-center text-muted" style={{ padding: 32 }}>
                    No categories found. Start by adding one.
                  </td>
                </tr>
              ) : (
                categories.map(cat => (
                  <tr key={cat.id} style={{ opacity: cat.isActive ? 1 : 0.55 }}>
                    <td>
                      <span
                        className="color-dot"
                        style={{ backgroundColor: cat.color, width: 16, height: 16 }}
                      />
                    </td>
                    <td className="fw-500">{cat.name}</td>
                    <td>
                      <span className={styles.typeChip}>
                        {typeLabel[cat.type] ?? cat.type}
                      </span>
                    </td>
                    <td>{fmt(cat.configuredAmount)}</td>
                    <td>
                      <span className={`badge ${cat.isActive ? 'badge-active' : 'badge-inactive'}`}>
                        {cat.isActive ? 'Active' : 'Archived'}
                      </span>
                    </td>
                    <td>
                      {cat.isActive && (
                        <button
                          className="btn-icon"
                          onClick={() => handleArchive(cat)}
                          title="Archive"
                          style={{ color: 'var(--yellow)' }}
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <polyline points="21 8 21 21 3 21 3 8" />
                            <rect x="1" y="3" width="22" height="5" />
                            <line x1="10" y1="12" x2="14" y2="12" />
                          </svg>
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Create Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Create Category"
        footer={
          <>
            <button className="btn btn-ghost" onClick={() => setIsModalOpen(false)}>Cancel</button>
            <button className="btn btn-primary" onClick={handleSave} disabled={isSaving}>
              {isSaving ? <><span className="spinner spinner-sm" />Saving...</> : 'Save'}
            </button>
          </>
        }
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="form-group">
            <label className="form-label">Category Name</label>
            <input
              className="form-input"
              type="text"
              placeholder="e.g. Groceries"
              value={form.name}
              onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
            />
            {formErrors.name && <span className="form-error">{formErrors.name}</span>}
          </div>
          <div className="form-group">
            <label className="form-label">Type</label>
            <select
              className="form-select"
              value={form.type}
              onChange={e => setForm(f => ({ ...f, type: e.target.value }))}
            >
              <option value="FIXED">Fixed Expense</option>
              <option value="MONTHLY_RESET">Monthly Budget</option>
              <option value="CUSTOM">Custom</option>
            </select>
          </div>
          <div className="form-group">
            <label className="form-label">Budget / Configured Amount (₹)</label>
            <input
              className="form-input"
              type="number"
              min="0"
              placeholder="5000"
              value={form.configuredAmount}
              onChange={e => setForm(f => ({ ...f, configuredAmount: e.target.value }))}
            />
          </div>
          <div className="form-group">
            <label className="form-label">Color</label>
            <div className={styles.colorRow}>
              <input
                type="color"
                className={styles.colorInput}
                value={form.color}
                onChange={e => setForm(f => ({ ...f, color: e.target.value }))}
              />
              <span className={styles.colorValue}>{form.color}</span>
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Description (Optional)</label>
            <input
              className="form-input"
              type="text"
              placeholder="Brief description"
              value={form.description}
              onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
            />
          </div>
        </div>
      </Modal>
    </div>
  );
}
