// frontend/src/app/features/expenses/expenses.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, CurrencyPipe, DatePipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDialog, MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';

@Component({
  selector: 'app-expense-dialog',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule
  ],
  template: `
    <h2 mat-dialog-title>{{ data?.expense ? 'Edit' : 'Add' }} Expense</h2>
    <mat-dialog-content>
      <form [formGroup]="form" class="d-flex flex-column gap-2 mt-2">
        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Date</mat-label>
          <input matInput type="date" formControlName="date">
        </mat-form-field>
        
        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Category</mat-label>
          <mat-select formControlName="categoryId">
            <mat-option *ngFor="let cat of data.categories" [value]="cat.id">
              {{ cat.name }}
            </mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Amount (₹)</mat-label>
          <input matInput type="number" formControlName="amount">
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-100">
          <mat-label>Description (Optional)</mat-label>
          <input matInput formControlName="description">
        </mat-form-field>
      </form>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button mat-dialog-close>Cancel</button>
      <button mat-raised-button color="primary" [disabled]="form.invalid" (click)="save()">Save</button>
    </mat-dialog-actions>
  `,
  styles: [`
    .flex-column { flex-direction: column; }
    .gap-2 { gap: 16px; }
  `]
})
export class ExpenseDialogComponent implements OnInit {
  fb = inject(FormBuilder);
  dialogRef = inject(MatDialogRef<ExpenseDialogComponent>);
  data = inject(MAT_DIALOG_DATA);

  form = this.fb.group({
    date: ['', Validators.required],
    categoryId: [null, Validators.required],
    amount: [null, [Validators.required, Validators.min(1)]],
    description: ['']
  });

  ngOnInit() {
    if (this.data?.expense) {
      const exp = this.data.expense;
      const dateStr = new Date(exp.date).toISOString().split('T')[0];
      this.form.patchValue({
        date: dateStr,
        categoryId: exp.categoryId,
        amount: exp.amount,
        description: exp.description
      });
    } else {
      const today = new Date().toISOString().split('T')[0];
      this.form.patchValue({ date: today });
    }
  }

  save() {
    if (this.form.valid) {
      this.dialogRef.close(this.form.value);
    }
  }
}

@Component({
  selector: 'app-expenses',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule
  ],
  providers: [CurrencyPipe, DatePipe],
  template: `
    <div class="header-section d-flex justify-between align-center mb-3">
      <h2>Expenses</h2>
      <button mat-raised-button color="primary" (click)="openDialog()">
        <mat-icon>add</mat-icon> Add Expense
      </button>
    </div>

    <div class="filters d-flex gap-2 mb-3">
      <mat-form-field appearance="outline">
        <mat-label>Month</mat-label>
        <input matInput type="month" (change)="onFilterChange($event, 'month')" [value]="currentMonth">
      </mat-form-field>
      
      <mat-form-field appearance="outline">
        <mat-label>Category</mat-label>
        <mat-select (selectionChange)="onFilterChange($event.value, 'category')">
          <mat-option value="">All Categories</mat-option>
          <mat-option *ngFor="let cat of categories" [value]="cat.id">{{ cat.name }}</mat-option>
        </mat-select>
      </mat-form-field>
    </div>

    <mat-card>
      <mat-card-content class="p-0">
        <div class="table-responsive">
          <table mat-table [dataSource]="expenses" class="w-100">
          
          <ng-container matColumnDef="date">
            <th mat-header-cell *matHeaderCellDef> Date </th>
            <td mat-cell *matCellDef="let element"> {{element.date | date:'mediumDate'}} </td>
          </ng-container>

          <ng-container matColumnDef="category">
            <th mat-header-cell *matHeaderCellDef> Category </th>
            <td mat-cell *matCellDef="let element">
              <span class="category-badge" [style.backgroundColor]="element.category.color">
                {{element.category.name}}
              </span>
            </td>
          </ng-container>

          <ng-container matColumnDef="amount">
            <th mat-header-cell *matHeaderCellDef> Amount </th>
            <td mat-cell *matCellDef="let element" class="fw-500"> {{element.amount | currency:'INR':'symbol':'1.0-0'}} </td>
          </ng-container>

          <ng-container matColumnDef="description">
            <th mat-header-cell *matHeaderCellDef> Description </th>
            <td mat-cell *matCellDef="let element" class="text-muted"> {{element.description || '-'}} </td>
          </ng-container>

          <ng-container matColumnDef="actions">
            <th mat-header-cell *matHeaderCellDef> Actions </th>
            <td mat-cell *matCellDef="let element">
              <button mat-icon-button color="primary" (click)="openDialog(element)" title="Edit">
                <mat-icon>edit</mat-icon>
              </button>
              <button mat-icon-button color="warn" (click)="deleteExpense(element)" title="Delete">
                <mat-icon>delete</mat-icon>
              </button>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
          <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
        </table>
        </div>
        
        <div *ngIf="expenses.length === 0" class="text-center p-3 text-muted">
          No expenses found for this period.
        </div>
      </mat-card-content>
    </mat-card>
  `,
  styles: [`
    .table-responsive { overflow-x: auto; }
    .p-0 { padding: 0 !important; }
    .p-3 { padding: 24px; }
    .gap-2 { gap: 16px; }
    .text-muted { color: #757575; }
    .fw-500 { font-weight: 500; }
    .category-badge {
      padding: 4px 8px;
      border-radius: 12px;
      font-size: 0.75rem;
      color: white;
      text-shadow: 0 0 2px rgba(0,0,0,0.5);
    }
  `]
})
export class ExpensesComponent implements OnInit {
  http = inject(HttpClient);
  dialog = inject(MatDialog);
  snackBar = inject(MatSnackBar);

  expenses: any[] = [];
  categories: any[] = [];
  displayedColumns = ['date', 'category', 'amount', 'description', 'actions'];
  
  currentMonth = '';
  selectedCategory = '';

  ngOnInit() {
    const now = new Date();
    this.currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
    this.loadCategories();
    this.loadExpenses();
  }

  loadCategories() {
    this.http.get('http://localhost:3000/api/categories').subscribe({
      next: (res: any) => {
        // Only active categories for adding new expenses
        this.categories = res.data;
      }
    });
  }

  loadExpenses() {
    let url = `http://localhost:3000/api/expenses?month=${this.currentMonth}`;
    if (this.selectedCategory) {
      url += `&categoryId=${this.selectedCategory}`;
    }
    
    this.http.get(url).subscribe({
      next: (res: any) => {
        this.expenses = res.data.expenses;
      }
    });
  }

  onFilterChange(event: any, type: string) {
    if (type === 'month') {
      this.currentMonth = event.target.value;
    } else if (type === 'category') {
      this.selectedCategory = event;
    }
    this.loadExpenses();
  }

  openDialog(expense?: any) {
    const activeCategories = this.categories.filter(c => c.isActive || (expense && expense.categoryId === c.id));
    
    const dialogRef = this.dialog.open(ExpenseDialogComponent, { 
      width: '400px',
      data: { categories: activeCategories, expense }
    });
    
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        if (expense) {
          this.http.put(`http://localhost:3000/api/expenses/${expense.id}`, result).subscribe({
            next: () => {
              this.snackBar.open('Expense updated successfully', 'Close', { duration: 3000 });
              this.loadExpenses();
            }
          });
        } else {
          this.http.post('http://localhost:3000/api/expenses', result).subscribe({
            next: () => {
              this.snackBar.open('Expense added successfully', 'Close', { duration: 3000 });
              this.loadExpenses();
            }
          });
        }
      }
    });
  }

  deleteExpense(expense: any) {
    if (confirm(`Delete expense of ₹${expense.amount} for ${expense.category.name}?`)) {
      this.http.delete(`http://localhost:3000/api/expenses/${expense.id}`).subscribe({
        next: () => {
          this.snackBar.open('Expense deleted', 'Close', { duration: 3000 });
          this.loadExpenses();
        }
      });
    }
  }
}

// frontend/src/app/(app)/expenses/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { useToast } from '@/components/Toast';
import Modal from '@/components/Modal';
import styles from './expenses.module.css';

function fmt(n: number) {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
}
function fmtDate(d: string) {
  return new Date(d).toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' });
}
function todayStr() { return new Date().toISOString().split('T')[0]; }
function nowYearMonth() {
  const n = new Date();
  return `${n.getFullYear()}-${String(n.getMonth() + 1).padStart(2, '0')}`;
}

interface ExpenseForm {
  date: string;
  categoryId: string;
  amount: string;
  description: string;
}

const emptyForm: ExpenseForm = { date: todayStr(), categoryId: '', amount: '', description: '' };

export default function ExpensesPage() {
  const showToast = useToast();
  const [expenses, setExpenses] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [currentMonth, setCurrentMonth] = useState(nowYearMonth());
  const [selectedCategory, setSelectedCategory] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingExpense, setEditingExpense] = useState<any>(null);
  const [form, setForm] = useState<ExpenseForm>(emptyForm);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => { loadCategories(); loadExpenses(); }, []);

  async function loadCategories() {
    try {
      const res = await api.get('/categories');
      setCategories(res.data);
    } catch {}
  }

  async function loadExpenses() {
    try {
      let url = `/expenses?month=${currentMonth}`;
      if (selectedCategory) url += `&categoryId=${selectedCategory}`;
      const res = await api.get(url);
      setExpenses(res.data.expenses);
    } catch {}
  }

  useEffect(() => { loadExpenses(); }, [currentMonth, selectedCategory]);

  function openAdd() {
    setEditingExpense(null);
    setForm({ ...emptyForm, date: todayStr() });
    setFormErrors({});
    setIsModalOpen(true);
  }

  function openEdit(expense: any) {
    setEditingExpense(expense);
    setForm({
      date: new Date(expense.date).toISOString().split('T')[0],
      categoryId: String(expense.categoryId),
      amount: String(expense.amount),
      description: expense.description ?? '',
    });
    setFormErrors({});
    setIsModalOpen(true);
  }

  function validateForm() {
    const e: Record<string, string> = {};
    if (!form.date) e.date = 'Date is required';
    if (!form.categoryId) e.categoryId = 'Category is required';
    if (!form.amount || Number(form.amount) < 1) e.amount = 'Amount must be at least ₹1';
    setFormErrors(e);
    return Object.keys(e).length === 0;
  }

  async function handleSave() {
    if (!validateForm()) return;
    setIsSaving(true);
    const payload = {
      date: form.date,
      categoryId: form.categoryId,
      amount: Number(form.amount),
      description: form.description,
    };
    try {
      if (editingExpense) {
        await api.put(`/expenses/${editingExpense.id}`, payload);
        showToast('Expense updated successfully', 'success');
      } else {
        await api.post('/expenses', payload);
        showToast('Expense added successfully', 'success');
      }
      setIsModalOpen(false);
      loadExpenses();
    } catch (err: any) {
      showToast(err.body?.message || 'Failed to save expense', 'error');
    } finally {
      setIsSaving(false);
    }
  }

  async function handleDelete(expense: any) {
    if (!confirm(`Delete expense of ${fmt(expense.amount)} for ${expense.category?.name}?`)) return;
    try {
      await api.delete(`/expenses/${expense.id}`);
      showToast('Expense deleted', 'success');
      loadExpenses();
    } catch {
      showToast('Failed to delete expense', 'error');
    }
  }

  const activeCategories = categories.filter(c =>
    c.isActive || (editingExpense && editingExpense.categoryId === c.id)
  );

  return (
    <div className="fade-in">
      <div className="page-header">
        <h1 className="page-title">Expenses</h1>
        <button className="btn btn-primary" onClick={openAdd}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" />
          </svg>
          Add Expense
        </button>
      </div>

      {/* Filters */}
      <div className={styles.filters}>
        <div className="form-group" style={{ minWidth: 160 }}>
          <label className="form-label">Month</label>
          <input
            className="form-input"
            type="month"
            value={currentMonth}
            onChange={e => setCurrentMonth(e.target.value)}
          />
        </div>
        <div className="form-group" style={{ minWidth: 180 }}>
          <label className="form-label">Category</label>
          <select
            className="form-select"
            value={selectedCategory}
            onChange={e => setSelectedCategory(e.target.value)}
          >
            <option value="">All Categories</option>
            {categories.map(c => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Table */}
      <div className="card" style={{ padding: 0 }}>
        <div className="table-wrapper" style={{ border: 'none', borderRadius: 'var(--radius-lg)' }}>
          <table className="data-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Description</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {expenses.length === 0 ? (
                <tr>
                  <td colSpan={5} className="text-center text-muted" style={{ padding: 32 }}>
                    No expenses found for this period.
                  </td>
                </tr>
              ) : (
                expenses.map(exp => (
                  <tr key={exp.id}>
                    <td>{fmtDate(exp.date)}</td>
                    <td>
                      <span className="cat-badge" style={{ backgroundColor: exp.category?.color }}>
                        {exp.category?.name}
                      </span>
                    </td>
                    <td className="fw-600" style={{ color: 'var(--red)' }}>{fmt(exp.amount)}</td>
                    <td className="text-muted">{exp.description || '—'}</td>
                    <td>
                      <div className={styles.actions}>
                        <button
                          className="btn-icon"
                          onClick={() => openEdit(exp)}
                          title="Edit"
                          style={{ color: 'var(--accent)' }}
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                            <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                          </svg>
                        </button>
                        <button
                          className="btn-icon"
                          onClick={() => handleDelete(exp)}
                          title="Delete"
                          style={{ color: 'var(--red)' }}
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <polyline points="3 6 5 6 21 6" />
                            <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
                            <path d="M10 11v6" /><path d="M14 11v6" />
                            <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
                          </svg>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingExpense ? 'Edit Expense' : 'Add Expense'}
        footer={
          <>
            <button className="btn btn-ghost" onClick={() => setIsModalOpen(false)}>Cancel</button>
            <button className="btn btn-primary" onClick={handleSave} disabled={isSaving}>
              {isSaving ? <><span className="spinner spinner-sm" />Saving...</> : 'Save'}
            </button>
          </>
        }
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="form-group">
            <label className="form-label">Date</label>
            <input
              className={`form-input ${formErrors.date ? '' : ''}`}
              type="date"
              value={form.date}
              onChange={e => setForm(f => ({ ...f, date: e.target.value }))}
            />
            {formErrors.date && <span className="form-error">{formErrors.date}</span>}
          </div>
          <div className="form-group">
            <label className="form-label">Category</label>
            <select
              className="form-select"
              value={form.categoryId}
              onChange={e => setForm(f => ({ ...f, categoryId: e.target.value }))}
            >
              <option value="">Select a category</option>
              {activeCategories.map(c => (
                <option key={c.id} value={c.id}>{c.name}</option>
              ))}
            </select>
            {formErrors.categoryId && <span className="form-error">{formErrors.categoryId}</span>}
          </div>
          <div className="form-group">
            <label className="form-label">Amount (₹)</label>
            <input
              className="form-input"
              type="number"
              min="1"
              placeholder="500"
              value={form.amount}
              onChange={e => setForm(f => ({ ...f, amount: e.target.value }))}
            />
            {formErrors.amount && <span className="form-error">{formErrors.amount}</span>}
          </div>
          <div className="form-group">
            <label className="form-label">Description (Optional)</label>
            <input
              className="form-input"
              type="text"
              placeholder="What was this for?"
              value={form.description}
              onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
            />
          </div>
        </div>
      </Modal>
    </div>
  );
}
