// frontend/src/app/features/auth/register.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule, 
    ReactiveFormsModule, 
    RouterModule,
    MatCardModule, 
    MatInputModule, 
    MatButtonModule,
    MatSnackBarModule,
    MatProgressSpinnerModule
  ],
  template: `
    <div class="auth-container">
      <mat-card class="auth-card">
        <mat-card-header>
          <mat-card-title>Register</mat-card-title>
          <mat-card-subtitle>Create your Finance Tracker account</mat-card-subtitle>
        </mat-card-header>
        
        <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
          <mat-card-content>
            <mat-form-field appearance="outline" class="w-100 mt-2">
              <mat-label>Name</mat-label>
              <input matInput formControlName="name" placeholder="John Doe">
              <mat-error *ngIf="registerForm.get('name')?.hasError('required')">Name is required</mat-error>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-100">
              <mat-label>Email</mat-label>
              <input matInput type="email" formControlName="email" placeholder="pat@example.com">
              <mat-error *ngIf="registerForm.get('email')?.hasError('required')">Email is required</mat-error>
              <mat-error *ngIf="registerForm.get('email')?.hasError('email')">Valid email required</mat-error>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-100">
              <mat-label>Password</mat-label>
              <input matInput type="password" formControlName="password">
              <mat-error *ngIf="registerForm.get('password')?.hasError('required')">Password is required</mat-error>
              <mat-error *ngIf="registerForm.get('password')?.hasError('minlength')">Minimum 6 characters</mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="w-100">
              <mat-label>Age (Optional)</mat-label>
              <input matInput type="number" formControlName="age">
            </mat-form-field>

            <mat-form-field appearance="outline" class="w-100">
              <mat-label>Monthly Salary (₹)</mat-label>
              <input matInput type="number" formControlName="monthlySalary">
            </mat-form-field>
          </mat-card-content>
          
          <mat-card-actions class="d-flex justify-between align-center px-3 mb-2">
            <a routerLink="/login" mat-button color="primary">Already have an account?</a>
            <button mat-raised-button color="primary" type="submit" [disabled]="registerForm.invalid || isLoading">
              <mat-spinner diameter="20" *ngIf="isLoading"></mat-spinner>
              <span *ngIf="!isLoading">Register</span>
            </button>
          </mat-card-actions>
        </form>
      </mat-card>
    </div>
  `,
  styles: [`
    .auth-container {
      min-height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #f5f5f5;
      padding: 24px;
    }
    .auth-card {
      width: 100%;
      max-width: 450px;
    }
    .px-3 { padding-left: 16px; padding-right: 16px; }
  `]
})
export class RegisterComponent {
  fb = inject(FormBuilder);
  authService = inject(AuthService);
  router = inject(Router);
  snackBar = inject(MatSnackBar);

  isLoading = false;
  
  registerForm = this.fb.group({
    name: ['', [Validators.required, Validators.minLength(2)]],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
    age: [null],
    monthlySalary: [0, [Validators.min(0)]]
  });

  onSubmit() {
    if (this.registerForm.valid) {
      this.isLoading = true;
      this.authService.register(this.registerForm.value).subscribe({
        next: (res) => {
          this.isLoading = false;
          this.snackBar.open('Registration successful', 'Close', { duration: 3000 });
          this.router.navigate(['/dashboard']);
        },
        error: (err) => {
          this.isLoading = false;
          const msg = err.error?.message || 'Registration failed.';
          this.snackBar.open(msg, 'Close', { duration: 5000 });
        }
      });
    }
  }
}

// frontend/src/app/(auth)/register/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/components/Toast';
import styles from '../auth-form.module.css';

export default function RegisterPage() {
  const { register } = useAuth();
  const router = useRouter();
  const showToast = useToast();

  const [form, setForm] = useState({
    name: '',
    email: '',
    password: '',
    age: '',
    monthlySalary: '0',
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isLoading, setIsLoading] = useState(false);

  function validate() {
    const e: Record<string, string> = {};
    if (!form.name || form.name.trim().length < 2) e.name = 'Name must be at least 2 characters';
    if (!form.email) e.email = 'Email is required';
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) e.email = 'Enter a valid email address';
    if (!form.password || form.password.length < 6) e.password = 'Password must be at least 6 characters';
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  function handleChange(field: string, value: string) {
    setForm(prev => ({ ...prev, [field]: value }));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;
    setIsLoading(true);
    try {
      await register({
        name: form.name,
        email: form.email,
        password: form.password,
        age: form.age ? Number(form.age) : null,
        monthlySalary: Number(form.monthlySalary) || 0,
      });
      showToast('Registration successful!', 'success');
      router.replace('/dashboard');
    } catch (err: any) {
      const msg = err.body?.message || 'Registration failed. Please try again.';
      showToast(msg, 'error');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className={styles.card}>
      <div className={styles.header}>
        <div className={styles.icon}>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
            <circle cx="12" cy="7" r="4" />
          </svg>
        </div>
        <h1 className={styles.title}>Create account</h1>
        <p className={styles.subtitle}>Start tracking your finances today</p>
      </div>

      <form onSubmit={handleSubmit} className={styles.form} noValidate>
        <div className="form-group">
          <label className="form-label">Full Name</label>
          <input
            className={`form-input ${errors.name ? styles.inputError : ''}`}
            type="text"
            placeholder="John Doe"
            value={form.name}
            onChange={e => handleChange('name', e.target.value)}
            autoComplete="name"
          />
          {errors.name && <span className="form-error">{errors.name}</span>}
        </div>

        <div className="form-group">
          <label className="form-label">Email Address</label>
          <input
            className={`form-input ${errors.email ? styles.inputError : ''}`}
            type="email"
            placeholder="you@example.com"
            value={form.email}
            onChange={e => handleChange('email', e.target.value)}
            autoComplete="email"
          />
          {errors.email && <span className="form-error">{errors.email}</span>}
        </div>

        <div className="form-group">
          <label className="form-label">Password</label>
          <input
            className={`form-input ${errors.password ? styles.inputError : ''}`}
            type="password"
            placeholder="Min. 6 characters"
            value={form.password}
            onChange={e => handleChange('password', e.target.value)}
            autoComplete="new-password"
          />
          {errors.password && <span className="form-error">{errors.password}</span>}
        </div>

        <div className={styles.twoCol}>
          <div className="form-group">
            <label className="form-label">Age (Optional)</label>
            <input
              className="form-input"
              type="number"
              placeholder="25"
              value={form.age}
              onChange={e => handleChange('age', e.target.value)}
              min="0"
            />
          </div>
          <div className="form-group">
            <label className="form-label">Monthly Salary (₹)</label>
            <input
              className="form-input"
              type="number"
              placeholder="50000"
              value={form.monthlySalary}
              onChange={e => handleChange('monthlySalary', e.target.value)}
              min="0"
            />
          </div>
        </div>

        <button type="submit" className={`btn btn-primary w-100 ${styles.submitBtn}`} disabled={isLoading}>
          {isLoading ? (
            <><span className="spinner spinner-sm" />Creating account...</>
          ) : 'Create Account'}
        </button>
      </form>

      <div className={styles.footer}>
        <span>Already have an account?</span>
        <Link href="/login" className={styles.link}>Sign in</Link>
      </div>
    </div>
  );
}
