// frontend/src/app/(app)/settings/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/components/Toast';
import styles from './settings.module.css';

export default function SettingsPage() {
  const { currentUser, refreshUser } = useAuth();
  const showToast = useToast();

  const [form, setForm] = useState({
    name: '',
    age: '',
    monthlySalary: '',
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSaving, setIsSaving] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    api.get('/profile')
      .then(res => {
        const user = res.data;
        setForm({
          name: user.name || '',
          age: user.age ? String(user.age) : '',
          monthlySalary: user.monthlySalary ? String(user.monthlySalary) : '0',
        });
      })
      .catch(() => showToast('Failed to load profile', 'error'))
      .finally(() => setIsLoading(false));
  }, [showToast]);

  function validate() {
    const e: Record<string, string> = {};
    if (!form.name.trim()) e.name = 'Name is required';
    if (Number(form.monthlySalary) < 0) e.monthlySalary = 'Salary cannot be negative';
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;
    setIsSaving(true);
    try {
      await api.put('/profile', {
        name: form.name,
        age: form.age ? Number(form.age) : null,
        monthlySalary: Number(form.monthlySalary),
      });
      showToast('Settings saved successfully', 'success');
      await refreshUser();
    } catch (err: any) {
      showToast(err.body?.message || 'Failed to save settings', 'error');
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="fade-in">
      <div className="page-header">
        <h1 className="page-title">Settings</h1>
      </div>

      <div className={`card ${styles.settingsCard}`}>
        <div className={styles.cardHeader}>
          <h2 className={styles.cardTitle}>Profile Information</h2>
          <p className="text-muted" style={{ fontSize: '0.875rem' }}>
            Update your personal and financial details
          </p>
        </div>

        {isLoading ? (
          <div className={styles.loadingState}>
            <div className="spinner" />
          </div>
        ) : (
          <form onSubmit={handleSubmit} className={styles.form}>
            <div className="form-group">
              <label className="form-label">Email Address</label>
              <input
                className="form-input"
                type="email"
                value={currentUser?.email || ''}
                disabled
              />
              <span className="text-muted" style={{ fontSize: '0.75rem', marginTop: 4 }}>
                Email cannot be changed
              </span>
            </div>

            <div className="form-group">
              <label className="form-label">Name</label>
              <input
                className={`form-input ${errors.name ? 'error' : ''}`}
                type="text"
                value={form.name}
                onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
              />
              {errors.name && <span className="form-error">{errors.name}</span>}
            </div>

            <div className={styles.twoCol}>
              <div className="form-group">
                <label className="form-label">Age</label>
                <input
                  className="form-input"
                  type="number"
                  min="0"
                  value={form.age}
                  onChange={e => setForm(f => ({ ...f, age: e.target.value }))}
                />
              </div>

              <div className="form-group">
                <label className="form-label">Monthly Salary (₹)</label>
                <input
                  className={`form-input ${errors.monthlySalary ? 'error' : ''}`}
                  type="number"
                  min="0"
                  value={form.monthlySalary}
                  onChange={e => setForm(f => ({ ...f, monthlySalary: e.target.value }))}
                />
                {errors.monthlySalary && <span className="form-error">{errors.monthlySalary}</span>}
              </div>
            </div>

            <div className={styles.actions}>
              <button type="submit" className="btn btn-primary" disabled={isSaving}>
                {isSaving ? <><span className="spinner spinner-sm" />Saving...</> : 'Save Changes'}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}

// frontend/src/app/features/settings/settings.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatSnackBar } from '@angular/material/snack-bar';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule
  ],
  template: `
    <div class="header-section mb-3">
      <h2>Settings</h2>
    </div>

    <mat-card class="settings-card">
      <mat-card-header>
        <mat-card-title>Profile Information</mat-card-title>
        <mat-card-subtitle>Update your personal and financial details</mat-card-subtitle>
      </mat-card-header>

      <form [formGroup]="profileForm" (ngSubmit)="saveProfile()">
        <mat-card-content class="d-flex flex-column gap-2 mt-3">
          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Email Address</mat-label>
            <input matInput [value]="authService.currentUser()?.email" disabled>
            <mat-hint>Email cannot be changed</mat-hint>
          </mat-form-field>

          <mat-form-field appearance="outline" class="w-100 mt-2">
            <mat-label>Name</mat-label>
            <input matInput formControlName="name">
          </mat-form-field>

          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Age</mat-label>
            <input matInput type="number" formControlName="age">
          </mat-form-field>

          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Monthly Salary (₹)</mat-label>
            <input matInput type="number" formControlName="monthlySalary">
          </mat-form-field>
        </mat-card-content>
        
        <mat-card-actions align="end" class="p-3">
          <button mat-raised-button color="primary" type="submit" [disabled]="profileForm.invalid || isSaving">
            Save Changes
          </button>
        </mat-card-actions>
      </form>
    </mat-card>
  `,
  styles: [`
    .settings-card { max-width: 600px; }
    .flex-column { flex-direction: column; }
    .gap-2 { gap: 16px; }
    .p-3 { padding: 16px 24px; }
  `]
})
export class SettingsComponent implements OnInit {
  fb = inject(FormBuilder);
  http = inject(HttpClient);
  snackBar = inject(MatSnackBar);
  authService = inject(AuthService);

  isSaving = false;

  profileForm = this.fb.group({
    name: ['', Validators.required],
    age: [null],
    monthlySalary: [0, [Validators.required, Validators.min(0)]]
  });

  ngOnInit() {
    this.http.get('http://localhost:3000/api/profile').subscribe({
      next: (res: any) => {
        const user = res.data;
        this.profileForm.patchValue({
          name: user.name,
          age: user.age,
          monthlySalary: Number(user.monthlySalary)
        });
      }
    });
  }

  saveProfile() {
    if (this.profileForm.valid) {
      this.isSaving = true;
      this.http.put('http://localhost:3000/api/profile', this.profileForm.value).subscribe({
        next: (res: any) => {
          this.isSaving = false;
          this.snackBar.open('Settings saved successfully', 'Close', { duration: 3000 });
          // Update the global state with new user info
          this.authService.getMe().subscribe();
        },
        error: (err) => {
          this.isSaving = false;
          this.snackBar.open('Failed to save settings', 'Close', { duration: 3000 });
        }
      });
    }
  }
}
